packages:
  - "apps/*"
  - "packages/*"
  - "backend/apps/*"
allowBuilds:
  "@medusajs/telemetry": false
  "@swc/core": false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false
  unrs-resolver: true
